SG-30560 Code cleanup for qt4 and pyside
shotgunsoftware/tk-multi-pythonconsole pull request #35
Opened 2024-05-22 19:06 UTC by eduardoChaucaGallegos

Code cleanup for qt4 and pyside

2024-05-23 17:17 UTC, julien-lang requested changes

2024-05-23 17:17 UTC, julien-lang commented on python/app/qt_importer.py
> -        from PySide import QtCore, QtGui
No, please remove the except ImportError: from PySide6 above to get the same behavior if we can't find a PySide interface

```python
    if not imported_qt:
        # Try PySide6
         from PySide6 import QtCore
         import PySide6.QtGui as __PySide_QtGui
         import PySide6.QtWidgets as __PySide_QtWidgets
    else:
        # Patch PySide2/PySide6 to keep the QtGui interface consi
        [...]
```

2024-05-23 17:17 UTC, julien-lang commented on python/app/ui/resources_rc.py
> +            pass
No, we want an ImportError raise eventually:

```python
try:
    from sgtk.platform.qt import QtCore
except ImportError:
    try:
        from PySide2 import QtCore
    except ImportError:
        from PySide6 import QtCore
```

2024-05-30 19:59 UTC, julien-lang approved these changes
LGTM!

2024-05-30 20:07 UTC, carlos-villavicencio-adsk requested changes

2024-05-30 20:07 UTC, carlos-villavicencio-adsk commented on python/app/qt_importer.py
> -        # Patch PySide2/PySide6 to keep the QtGui interface consistent with PySide (Qt 4).
We still use the Qt interface consistent with Qt4. Please revert this comment.

2024-05-30 20:07 UTC, carlos-villavicencio-adsk commented on python/app/qt_importer.py
> +qt_re_module_is_regular_expression = True
Unfortunately, this requires more work on python/app/syntax_highlighter.py.

You can take a look at #25. Probably it's worth removing dead code such as `match_multiline_regexp` and `highlight_block_regexp`.

2024-06-03 20:04 UTC, carlos-villavicencio-adsk approved these changes
LGTM! Thanks

2024-06-19 22:27 UTC, merged